# Generated by Django 5.2.11 on 2026-02-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice1',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Choice 1'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice2',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Choice 2'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice3',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Choice 3'),
        ),
    ]
