# Generated by Django 5.2.11 on 2026-02-27 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_choice1_question_choice2_question_choice3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choice1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice3',
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Choice Text')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is Correct?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='questions.question', verbose_name='Question')),
            ],
        ),
    ]
