# Generated by Django 5.2.11 on 2026-02-27 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_remove_question_choice1_remove_question_choice2_and_more'),
        ('questions', '0004_comment'),
    ]

    operations = [
    ]
