# Generated by Django 5.2.11 on 2026-02-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_merge_20260227_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, help_text='Only for Short Answer type questions', null=True, verbose_name='Correct Answer'),
        ),
    ]
